global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8082']

  - job_name: 'wellness-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['wellness-service:8083']

  - job_name: 'goal-tracking-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['goal-tracking-service:8084']

  - job_name: 'event-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['event-service:8085']